/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vegentory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class HapusDataWargaKelurahan extends javax.swing.JFrame {

    /**
     * Creates new form HapusDataWargaKelurahan
     */
    public HapusDataWargaKelurahan() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lihatdatawargakelurahan = new javax.swing.JPanel();
        lihatdatawargakelurahanbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellihatdatawargakelurahan = new javax.swing.JTable();
        backbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        hapusdatawargakelurahanfield = new javax.swing.JTextField();
        hapusbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Hapus Data Warga Kelurahan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        lihatdatawargakelurahan.setBackground(new java.awt.Color(204, 204, 204));

        lihatdatawargakelurahanbutton.setText("Lihat Data");
        lihatdatawargakelurahanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatdatawargakelurahanbuttonActionPerformed(evt);
            }
        });

        tabellihatdatawargakelurahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Wilayah", "Nama Kelurahan", "Jumlah Penduduk", "Konsumsi Rata Rata", "Pendapatan Rata Rata"
            }
        ));
        jScrollPane1.setViewportView(tabellihatdatawargakelurahan);

        backbutton.setText("Kembali");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Untuk menghapus data sebuah kelurahan, masukkan kode_wilayah kelurahan tersebut");

        hapusdatawargakelurahanfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusdatawargakelurahanfieldActionPerformed(evt);
            }
        });

        hapusbutton.setText("HAPUS");
        hapusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lihatdatawargakelurahanLayout = new javax.swing.GroupLayout(lihatdatawargakelurahan);
        lihatdatawargakelurahan.setLayout(lihatdatawargakelurahanLayout);
        lihatdatawargakelurahanLayout.setHorizontalGroup(
            lihatdatawargakelurahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatdatawargakelurahanLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(backbutton)
                .addGap(214, 214, 214)
                .addGroup(lihatdatawargakelurahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lihatdatawargakelurahanLayout.createSequentialGroup()
                        .addComponent(hapusdatawargakelurahanfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(hapusbutton)
                        .addGap(81, 81, 81)))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lihatdatawargakelurahanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lihatdatawargakelurahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lihatdatawargakelurahanLayout.createSequentialGroup()
                        .addComponent(lihatdatawargakelurahanbutton)
                        .addGap(388, 388, 388))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lihatdatawargakelurahanLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        lihatdatawargakelurahanLayout.setVerticalGroup(
            lihatdatawargakelurahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatdatawargakelurahanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lihatdatawargakelurahanbutton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(lihatdatawargakelurahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lihatdatawargakelurahanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lihatdatawargakelurahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backbutton)
                            .addComponent(hapusdatawargakelurahanfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapusbutton))
                        .addGap(84, 84, 84))
                    .addGroup(lihatdatawargakelurahanLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)
                        .addContainerGap(133, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lihatdatawargakelurahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lihatdatawargakelurahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusdatawargakelurahanfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusdatawargakelurahanfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusdatawargakelurahanfieldActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        WargaKelurahan obj =new WargaKelurahan();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void lihatdatawargakelurahanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatdatawargakelurahanbuttonActionPerformed
        // TODO add your handling code here:
String connectionUrl =
                "jdbc:sqlserver://LAPTOP-3UBO9HRP;"
                + "database=Vegentory;"
                + "user=sa;"
                + "password=12345678;"
                + "encrypt=false;"
                + "trustServerCertificate=false;"
                + "loginTimeout=30;";

        java.sql.ResultSet rs = null;

        try (Connection connection = DriverManager.getConnection(connectionUrl);
                Statement statement = connection.createStatement();) {

            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT * from warga_kelurahan;";
            rs = statement.executeQuery(selectSql);
//             Print results from select statement
            DefaultTableModel tm=(DefaultTableModel)tabellihatdatawargakelurahan.getModel();
            tm.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getInt("kode_wilayah"),rs.getString("nama_kelurahan"),rs.getInt("jumlah_penduduk"),rs.getInt("konsumsi_rataRata"),rs.getInt("pendapatan_rataRata")};
                tm.addRow(o);
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_lihatdatawargakelurahanbuttonActionPerformed

    private void hapusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbuttonActionPerformed
        // TODO add your handling code here:
       String fid = hapusdatawargakelurahanfield.getText();
try {
    String connectionUrl =
        "jdbc:sqlserver://LAPTOP-3UBO9HRP;"
        + "database=Vegentory;"
        + "user=sa;"
        + "password=12345678;"
        + "encrypt=false;"
        + "trustServerCertificate=false;"
        + "loginTimeout=30;";
    
    Connection conn = DriverManager.getConnection(connectionUrl);

    // Gunakan PreparedStatement untuk menghindari SQL injection
    String sql = "DELETE FROM warga_kelurahan WHERE kode_wilayah=?";
    try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
        // Set parameter sesuai tipe data kolom
        pstmt.setInt(1, Integer.parseInt(fid));
        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data deleted successfully");
    }

    // Jangan lupa menutup koneksi
    conn.close();
    hapusdatawargakelurahanfield.setText("");
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
            
    }//GEN-LAST:event_hapusbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HapusDataWargaKelurahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HapusDataWargaKelurahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HapusDataWargaKelurahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HapusDataWargaKelurahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HapusDataWargaKelurahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton hapusbutton;
    private javax.swing.JTextField hapusdatawargakelurahanfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lihatdatawargakelurahan;
    private javax.swing.JButton lihatdatawargakelurahanbutton;
    private javax.swing.JTable tabellihatdatawargakelurahan;
    // End of variables declaration//GEN-END:variables
}
